<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="Daniels-MBP.lan" name="pytest" skipped="0" tests="3" time="1.107" timestamp="2020-06-19T16:41:33.596289"><testcase classname="tests.test_basic" file="tests/test_basic.py" line="11" name="test_urlnotvailid" time="0.001"></testcase><testcase classname="tests.test_basic" file="tests/test_basic.py" line="14" name="test_filenotexists" time="0.001"></testcase><testcase classname="tests.test_basic" file="tests/test_basic.py" line="17" name="test_checklogin" time="0.001"><failure message="AssertionError: assert &apos;Bearer&apos; in &apos;Error: File does not exist&apos;
 +  where &apos;Error: File does not exist&apos; = main(&apos;https://mingle-sso.eu1.inforcloudsuite.com:443/BVB_DEV&apos;, &apos;FellowKey.ionapi&apos;, &apos;checklogin&apos;)">def test_checklogin():
&gt;       assert  &quot;Bearer&quot; in main(&quot;https://mingle-sso.eu1.inforcloudsuite.com:443/BVB_DEV&quot;,&quot;FellowKey.ionapi&quot;,&quot;checklogin&quot;)
E       AssertionError: assert &apos;Bearer&apos; in &apos;Error: File does not exist&apos;
E        +  where &apos;Error: File does not exist&apos; = main(&apos;https://mingle-sso.eu1.inforcloudsuite.com:443/BVB_DEV&apos;, &apos;FellowKey.ionapi&apos;, &apos;checklogin&apos;)

test_basic.py:19: AssertionError</failure></testcase></testsuite></testsuites>